install/swiftly-install.sh
The repo has been moved to `swift-server` and trying to access the release from `patrickfreed` no longer works.
=> Fix outdated download url

.gitignore, Sources/Swiftly/Swiftly.swift
Resolves #38.
~~Also see https://github.com/apple/swift-argument-parser/issues/563.~~ Thanks to Nate Cook for the response.
Quoting:
> `ParsableCommand` types provide this behavior (printing help by default) through the default implementation of the `run()` method. Since the `swiftly` command provides [an empty implementation](https://github.com/swift-server/swiftly/blob/main/Sources/Swiftly/Swiftly.swift#L36), that isn't done. You can either remove that implementation or print the result of `Swiftly.helpMessage()` from within that method.
```bash
Building for debugging...
Build complete! (0.50s)
```
```bash
Building for debugging...
Build complete! (0.50s)
OVERVIEW: A utility for installing and managing Swift toolchains.
USAGE: swiftly <subcommand>
OPTIONS:
--version               Show …
```
=> Show help message when no subcommands are provided

docker/install-test.dockerfile, docker/test.dockerfile, install/swiftly-install.sh, install/test-util.sh, install/tests/custom-home-install.sh, install/tests/custom-install.sh, install/tests/custom-tilde-install.sh, install/tests/default-install.sh, install/tests/disable-prompt.sh, install/tests/no-install-dependencies.sh, install/tests/overwrite.sh, install/tests/update-bash-profile.sh, install/tests/update-zprofile.sh
Closes #32
This works by scraping the dependency list from the dockerfiles at https://github.com/apple/swift-docker. Long-term, we'll want to get the list of dependencies from a swift.org API.
The design originally called for us to not do this due to different Swift releases having different system dependencies, but upon further reflection, this seems like a big enough ergonomic win that we might as well do it.
=> Install system dependencies in swiflty-install.sh

install/swiftly-install.sh, install/tests/custom-install.sh, install/tests/default-install.sh, install/tests/disable-prompt.sh
This fixes a bug similar to the one identified in #51, wherein `curl ... | bash` installation would fail due to stdin being EOF. In this case, `apt-get` was hanging because it needed some input to install the `tzdata` package. To address this, I've updated the system deps installation phase to just always proceed without confirmation. If a user wants to disable the installation of system deps, they already had to confirm as much during the options prompting phase.
=> Always disable confirmation when installing system dependencies

Sources/SwiftlyCore/ToolchainVerison.swift, Tests/SwiftlyTests/ToolchainSelectorTests.swift
This PR changes `ToolchainSelector` parsing to now accept inputs such as `5.7-SNAPSHOT` or `main-SNAPSHOT`. I opted not to add `swift-SNAPSHOT` as an alternative for `main-snapshot` since it would be another set of words we'd be accepting, whereas `main-SNAPSHOT` is only a difference of capitalization from the existing `main-snapshot`.
=> Accept SNAPSHOT in toolchain selector parsing

docker/install-test-amazonlinux2.dockerfile, install/swiftly-install.sh, install/tests/platform-option.sh
=> Support installation on alternative platforms

Sources/Swiftly/Use.swift, Tests/SwiftlyTests/UseTests.swift
=> Print the currently in-use toolchain if no argument is provided to use

Sources/SwiftlyCore/ToolchainVerison.swift, Tests/SwiftlyTests/ToolchainSelectorTests.swift
=> Support "swift-" prefix when parsing release snapshot selectors

README.md, Sources/Swiftly/Install.swift, Sources/Swiftly/ListAvailable.swift, Sources/Swiftly/Swiftly.swift, Sources/Swiftly/Uninstall.swift, Sources/Swiftly/Update.swift, Sources/Swiftly/Use.swift, Sources/SwiftlyCore/HTTPClient+GitHubAPI.swift, Sources/SwiftlyCore/HTTPClient.swift, Sources/SwiftlyCore/ToolchainVerison.swift, Sources/SwiftlyCore/Utils.swift, Tests/SwiftlyTests/InstallTests.swift, Tests/SwiftlyTests/ListTests.swift, Tests/SwiftlyTests/SwiftlyTests.swift, Tests/SwiftlyTests/UpdateTests.swift, Tests/SwiftlyTests/UseTests.swift
Closes #5 
See the README or the `--help` output in `Update.swift` for information on the semantics of the command.
=> Implement update command

Sources/Swiftly/Install.swift, Sources/Swiftly/Update.swift, Tests/SwiftlyTests/InstallTests.swift, Tests/SwiftlyTests/SwiftlyTests.swift
=> Add --use flag to install

install/run-tests.sh, install/swiftly-install.sh, install/test-util.sh, install/tests/disable-prompt.sh, install/tests/overwrite.sh, install/tests/platform-option.sh, install/tests/update-bash-profile.sh
Closes #83, also fixes #82
This PR updates the default behavior of swiftly-install.sh when an existing installation exists from prompting to perform a clean installation (i.e. delete all existing configuration and installed toolchains) to simply replacing the swiftly binary. Users can opt into the old behavior (without prompting) by using a newly introduced `--overwrite` option.
Going forward, most users will update swiftly via the `self-update` command introduced in #81, but since the current released swiftly version doesn't have that command, I think we need to provide a path through `swiftly-install.sh`. Furthermore, it would be too easy to accidentally delete your swiftly installation with the old default behavior, given that there isn't another supported means of upgrading.
Once this …
=> Support updating exsting swiftly installation from swiftly-install.sh

Sources/Swiftly/Uninstall.swift, Tests/SwiftlyTests/UninstallTests.swift
Hello, I maintain the [swiftly-bin AUR package](https://aur.archlinux.org/packages/swiftly-bin), and I appreciate all of the work that has gone into this utility, as it has been very useful to use (and definitely more flexible than just using the swift-bin AUR package!)
The [.install script](https://aur.archlinux.org/cgit/aur.git/tree/swiftly-bin.install?h=swiftly-bin) I wrote for said package runs `swiftly uninstall latest` in a loop until the `~/.local/share/swiftly/toolchains` folder is empty. This is prone to an infinite loop if a non-toolchain file or folder is placed in that directory.
To alleviate this, I propose some small changes to Uninstall.swift that allow for a one-command uninstallation of all installed toolchains with `swiftly uninstall all.`
I am new to contributing, so …
=> "swiftly uninstall all" command to remove all installed toolchains

Sources/SwiftlyCore/HTTPClient+GitHubAPI.swift, Tests/SwiftlyTests/SelfUpdateTests.swift
fixes #89 
I'm not sure that this is in line with the design intent, but I confirm that the problem has been resolved.
```console
$ swift run swiftly self-update
Building for debugging...
Build complete! (0.35s)
Checking for swiftly updates...
Already up to date.
```
=> fix: fix decoding error in `self-update` (#89)

install/swiftly-install.sh, install/tests/update-fish-config.sh
resolves #72
I added support for fish to `swiftly-install.sh`.
I added a unit test and confirm that all tests have passed by running `docker compose up install-test`. And of course, I tested that I could run `swiftly` after clean installation on my real environment.
=> feat: support fish shell in swiftly-install.sh (#72)

Sources/LinuxPlatform/Linux.swift, Sources/Swiftly/Install.swift, Sources/Swiftly/Update.swift, Sources/SwiftlyCore/HTTPClient.swift, Sources/SwiftlyCore/Platform.swift, Tests/SwiftlyTests/SwiftlyTests.swift, Tests/SwiftlyTests/UpdateTests.swift, docker/install-test-amazonlinux2.dockerfile, docker/install-test-ubi9.dockerfile, docker/install-test.dockerfile, docker/test-amazonlinux2.dockerfile, docker/test-ubi9.dockerfile, docker/test.dockerfile, install/swiftly-install.sh, install/tests/default-install.sh
=> Verify signatures of toolchains before installing

install/swiftly-install.sh
fixes #104 
This is a follow-up pull request of #91.
This pull request doesn't contain changes for fish users who have already installed swiftly.
I also checked output files and output messages in addition to `docker compose up install-test`.
```console
$ rm -rf ~/.local/bin/swiftly ~/.config/fish/conf.d/swiftly.fish ~/.local/share/swiftly
$ ./install/swiftly-install.sh --no-install-system-deps
Fedora Linux Asahi Remix 39 (Thirty Nine) is not an officially supported platform, but the toolchains for another platform may still work on it.
Please select the platform to use for toolchain downloads:
0) Cancel
1) Ubuntu 22.04
2) Ubuntu 20.04
3) Ubuntu 18.04
4) RHEL 9
5) Amazon Linux 2
> 1
This script will install swiftly, a Swift toolchain installer and manager.
Current installation options: …
```
=> fix(install): use `source` instead of `.` in fish

Package.resolved, Package.swift, Sources/SwiftlyCore/HTTPClient.swift, scripts/install-libarchive.sh
Reduce the use of unsafe swift constructs in favour of ones that are memory safe. In the HTTP client remove the use of the unsafe mutable pointer in favour of direct Data conversion before writing the downloaded file to disk.
Upgrade the version of libarchive to 3.7.4 with various fixes.
Upgrade the async http client to fix an issue with decompression limits encountered with the GitHub REST API's.
=> Update usage of unsafe API, upgrade libarchive to 3.7.4, upgrade async http client

Sources/SwiftlyCore/HTTPClient.swift
Sometimes, when not using a GitHub access token, the API returns a content-length that is shorter than the true length of the response body, which causes NIO to throw the error because there are remaining bytes in the payload.
The upTo parameter for collect is not intended to be used in this way. It acts as an upper limit to the size of a reasonable response, which prevents excessive memory consumption attempting to process it.
Instead of setting the upTo to the length given by the response, set the upper limit to something static that is an expected limit to the size that is expected. In the case of JSON, set it to 1MB.
This fixes #128
=> Fix NIOTooManyBytesError that sometimes occurs during XCTests

Package.resolved, Package.swift, docker/lint.dockerfile, docker/test-amazonlinux2.dockerfile, docker/test-ubi9.dockerfile, docker/test.dockerfile, scripts/check-lint.sh
The SwiftFormat that is run in the CI is a very specific version that is unlikely to be the one a dev has installed with homebrew or discovered for themselves and built from source. Discovering the version involves finding the magic in the lint.dockerfile.
SwiftPM provides a mechanism for bringing in product dependencies so that you can simply run using the toolchain. The dependencies can be specified using an exact match on a particular version. These products from the dependencies can be discovered using the `swift package describe` command, and perhaps someday Swift devs will discover a package's dev tools in this way.
Add the SwiftFormat dependency as a package dependency in swiftly at the version that is currently used in the soundness CI checks. Use the the swift command to invoke …
=> Integrate SwiftFormat into the swiftly project dependencies

RELEASING.md, Tools/build-swiftly-release/BuildSwiftlyRelease.swift
When building macOS packages with pkgbuild, a signing certificate needs to be provided up-front, as is the package identifier. Change the package script so that it can accept the location of the certificate and override the package identifier.
=> Add signature cert and package identifier parameters to package script

Sources/LinuxPlatform/Linux.swift
On Debian/Ubuntu Linux that use the dpkg/apt package manager there is a possibility that a package is not in a fully installed state. It can be removed, leaving its configuration files, or the install could have failed. Check rigorously that the package is fully installed without error before producing the command-line.
Also, correct the install command to use apt-get instead of apt since that command-line is guaranteed to be stable.
=> Fix package install detection for packages that are partially installed

Tools/build-swiftly-release/BuildSwiftlyRelease.swift
The libarchive that is used to make a swiftly release for Linux is downloaded directly from the libarchive project on GitHub from a release artifact. In theory, this release could become tampered in the future.
Typically package managers get around this problem by both getting a specific version of the package, and also keep a hash/git commit to verify the contents.
Add a content check using an expected SHA-256 sum of the release source tarball of libarchive to help protect against any tampering of the release in the future.
=> Verify the libarchive payload

Documentation/SwiftlyDocs.docc/getting-started.md, Sources/SwiftlyCore/HTTPClient.swift, Tests/SwiftlyTests/SwiftlyTests.swift
Read http_proxy/https_proxy/HTTP_PROXY/HTTPS_PROXY standard environment variables; and set `HTTPClient()` proxy configuration with one of the values.
Fixes https://github.com/swiftlang/swiftly/issues/108
@cmcgee1024 - this adds the minimal silent use based on the environment. Most tools read one of those variables.
=> Download toolchains using proxy if one is set in the environment

.github/workflows/build_release.yml, .github/workflows/pull_request.yml, Documentation/SwiftlyDocs.docc/swiftly-cli-reference.md
There's nothing in the pull request verification that checks if the command-line references are up-to-date. Add a job to the pull request update workflow that verifies this.
There's nothing in the release build workflow that generates the documentation and uploads the documentation artifacts so that they can be published. Add a step to the build release job that generates the documentation so that it can be published to swift.org.
=> Add documentation related build and checks to GitHub workflows

Tools/build-swiftly-release/BuildSwiftlyRelease.swift
When operating on Linux there are different variants of swiftly for either x86_64 or aarch64 architectures. It is likely that people will need to make platform-independent samples, such as on swift.org to download the correct binary package for their system. By making the filename reflect what `uname -m` on the system scripts can use this to make sure that they download the correct release package and also they can download both without collisions. Fix the release package filename for linux x86_64 to include the architecture in the file name so that the filename matches the following:
`swiftly-<VERSION>-$(uname -m).tar.gz`
=> Make release package file names more uname friendly on Linux

Sources/SwiftlyCore/Error.swift, Tools/build-swiftly-release/BuildSwiftlyRelease.swift
`swift-argument-parser` will use an Error's description when printing the error. This patch conforms Swiftly's Error type to CustomStringConvertible, which will show the actual message in stdout instead of the object's description of `Error(message: "...")`
Issue: #201
=> Conform Swiftly's Error type to CustomStringConvertible

Package.resolved, Package.swift, Sources/LinuxPlatform/Linux.swift, Sources/MacOSPlatform/MacOS.swift, Sources/Swiftly/Config.swift, Sources/Swiftly/Init.swift, Sources/Swiftly/Install.swift, Sources/Swiftly/ListAvailable.swift, Sources/Swiftly/Proxy.swift, Sources/Swiftly/Run.swift, Sources/Swiftly/SelfUpdate.swift, Sources/Swiftly/Swiftly.swift, Sources/Swiftly/Update.swift, Sources/Swiftly/Use.swift, Sources/SwiftlyCore/Error.swift, Sources/SwiftlyCore/HTTPClient.swift, Sources/SwiftlyCore/Platform.swift, Sources/SwiftlyCore/SwiftlyVersion.swift, Sources/SwiftlyCore/ToolchainVersion.swift, Sources/SwiftlyCore/openapi-generator-config.yaml, Sources/SwiftlyCore/openapi.yaml, Tests/SwiftlyTests/HTTPClientTests.swift, Tests/SwiftlyTests/RunTests.swift, Tests/SwiftlyTests/SwiftlyTests.swift
Use the OpenAPI specification for the swift.org API and the swift OpenAPI generation capabilities to avoid having to hand craft the HTTP handling and local data types.
=> Adopt OpenAPI for fetching current swiftly releases

.github/workflows/build_release.yml, Sources/Swiftly/Init.swift, Sources/SwiftlyCore/SwiftlyCore.swift
Update the version of swiftly. Add a self-upgrade routine from 0.4.0-dev.
=> Prepare for the 0.4.0 release

swiftly-install.sh
The `--no-import-pgp-keys` option was not being passed to `getopt`, causing use of the flag to fail with `swiftly-install: unrecognized option '--no-import-pgp-keys'`.
=> Add --no-import-pgp-keys to long options for getopt

Documentation/SwiftlyDocs.docc/getting-started.md
Bring some of the swift versions to something more recent.
Remove the linux specifics from the parts that are platform
independent.
=> Getting started guide cleanup

Sources/SwiftlyCore/ToolchainVersion.swift, Tests/SwiftlyTests/ToolchainSelectorTests.swift
Existing tools like `swiftenv` use `DEVELOPMENT-SNAPSHOT-YYYY-mm-dd-a` for main snapshots, without the `swift-` prefix. The `MainSnapshotParser` should be able to handle this and this change mirrors the `ReleaseSnapshotParser` in this regard, which already supports both `swift-` prefixed and unprefixed versions.
=> Make "swift-" prefix optional in MainSnapshotParser

Sources/LinuxPlatform/Linux.swift, Sources/MacOSPlatform/MacOS.swift, Sources/SwiftlyCore/HTTPClient.swift, Sources/SwiftlyCore/SwiftlyCore.swift, Tests/SwiftlyTests/HTTPClientTests.swift, Tests/SwiftlyTests/SwiftlyTests.swift
- Move arch string literal to a global variable `cpuArch`.
- Refactor: Let compiler to infer the array type.
=> Add a global variable cpuArch

Sources/MacOSPlatform/MacOS.swift, Sources/Swiftly/Use.swift
Swiftly interpolates some file URLs directly into user facing output leading to messages like 'The file `file:///Volumes/...` has been...' which needlessly contains the url schema prefix `file://`. This change updates Swiftly to use URL.path for better user output.
=> Print file URLs without leading file schema

Package.resolved, Package.swift
Swift NIO 2.80.0 contains a workaround for a miscompile which causes swiftly to hang. Specifically code like `@usableFromInline let _free: @convention(c) [...] = { free($0) }` miscompiles into a CPU spin loop on some builds of `swift`.
=> Update Swift NIO dependency

Sources/LinuxPlatform/Linux.swift, Sources/MacOSPlatform/MacOS.swift, Sources/Swiftly/Init.swift, Sources/Swiftly/Install.swift, Sources/Swiftly/Proxy.swift, Sources/Swiftly/Run.swift, Sources/Swiftly/Uninstall.swift, Sources/Swiftly/Update.swift, Sources/Swiftly/Use.swift, Sources/SwiftlyCore/Platform.swift, Sources/SwiftlyCore/SwiftlyCore.swift, Tests/SwiftlyTests/PlatformTests.swift, Tests/SwiftlyTests/UninstallTests.swift, Tests/SwiftlyTests/UpdateTests.swift
Update the main branch with the fixes. Establish a fresh version with upgrade path from the release made from the 1.0 branch.
=> Merge updates from release/1.0 to the main branch

Sources/LinuxPlatform/Linux.swift, Sources/Swiftly/Init.swift, Sources/Swiftly/Install.swift, Sources/Swiftly/Use.swift
Change Debian 12 binutils-gold virtual package to binutils
Move some progress indications under verbose flag for shorter default install log
=> Remove rehashing instructions when using the fish shell

Sources/LinuxPlatform/Linux.swift, Sources/Swiftly/Init.swift, Sources/Swiftly/Install.swift
Change Debian 12 binutils-gold virtual package to binutils
Move some progress indications under verbose flag for shorter default install log
=> Remove rehashing instructions when using the fish shell (#250)

DESIGN.md, Documentation/SwiftlyDocs.docc/automated-install.md, Documentation/SwiftlyDocs.docc/swiftly-cli-reference.md, Documentation/SwiftlyDocs.docc/uninstall-toolchains.md, Sources/LinuxPlatform/Extract.swift, Sources/LinuxPlatform/Linux.swift, Sources/Swiftly/Config.swift, Sources/Swiftly/Init.swift, Sources/Swiftly/List.swift, Sources/Swiftly/ListAvailable.swift, Sources/Swiftly/Run.swift, Sources/Swiftly/SelfUpdate.swift, Sources/Swiftly/Swiftly.swift, Sources/Swiftly/Update.swift, Sources/Swiftly/Use.swift, Sources/SwiftlyCore/HTTPClient.swift, Sources/SwiftlyCore/Platform.swift, Tests/SwiftlyTests/E2ETests.swift, Tests/SwiftlyTests/InitTests.swift, Tests/SwiftlyTests/InstallTests.swift, Tests/SwiftlyTests/UpdateTests.swift, Tools/build-swiftly-release/BuildSwiftlyRelease.swift
- Omitted `internal` access control because of no need in explicit declaration as it is default
- Following SE-0345 refactored if let constructions
- Fixed typos
- Some general code enhancements
=> feature: Omit internal access control, if let shorthand, fix typos

Sources/LinuxPlatform/Linux.swift, Sources/MacOSPlatform/MacOS.swift, Sources/Swiftly/Init.swift, Sources/SwiftlyCore/Platform.swift, Tests/SwiftlyTests/SwiftlyTests.swift, Tests/SwiftlyTests/UninstallTests.swift, Tools/build-swiftly-release/BuildSwiftlyRelease.swift
Correct productbuild issue when creating a pkg from synthesized
distribution.xml.
Fix quiet option so that it doesn't prevent the environment file from
being added to the profile.
=> Change the default install path for macOS pkgs

Documentation/SwiftlyDocs.docc/SwiftlyDocs.md, Documentation/SwiftlyDocs.docc/automated-install.md, Documentation/SwiftlyDocs.docc/install-toolchains.md, Documentation/SwiftlyDocs.docc/shell-autocompletion.md, Documentation/SwiftlyDocs.docc/uninstall-toolchains.md, Documentation/SwiftlyDocs.docc/update-toolchain.md, Documentation/SwiftlyDocs.docc/use-toolchains.md
Updates the DocC content to make abstracts for each of the guide articles:
- renames the topic header from `HOWTOS` to `Guides`.
- sets an explicit abstract for each guide and makes them complete sentences to flow better on the top-level page.
=> updates the abstracts for each of the HowTo guides, and renames the topic heading from 'HOWTOS' to 'Guides'

Documentation/SwiftlyDocs.docc/SwiftlyDocs.md, Documentation/SwiftlyDocs.docc/automated-install.md, Documentation/SwiftlyDocs.docc/install-toolchains.md, Documentation/SwiftlyDocs.docc/shell-autocompletion.md, Documentation/SwiftlyDocs.docc/uninstall-toolchains.md, Documentation/SwiftlyDocs.docc/update-toolchain.md, Documentation/SwiftlyDocs.docc/use-toolchains.md
Updates the abstracts for each of the HowTo guides, and renames the topic heading from 'HOWTOS' to 'Guides'.
=> Update the abstracts for the HowTo guides, Rename HOWTOS to Guides

DESIGN.md
There's no such product or entity as "SPM", this contraction is just as invalid as "MOS" would be for macOS, or "SNIO" for SwiftNIO. All marketing and documentation materials consistently refer to it as "SwiftPM", and we should stay consistent in our codebase too. This also simplifies code search, as anything named as "SPM" almost never shows up in results when searching globally for "SwiftPM".
=> Fix typo in `DESIGN.md`

Sources/Swiftly/Init.swift, Sources/Swiftly/Install.swift, Sources/Swiftly/Update.swift
This applies some polishing on the textual output of the command line tool, namely:
* Inline the `hash -r` advice.
* Mention the location where toolchains go.
* Improve text a little generally.
* Restructure the code to built up the message.
=> Polish welcome message

Documentation/SwiftlyDocs.docc/SwiftlyDocs.md, Documentation/SwiftlyDocs.docc/automated-install.md, Documentation/SwiftlyDocs.docc/getting-started.md, Documentation/SwiftlyDocs.docc/install-toolchains.md, Documentation/SwiftlyDocs.docc/shell-autocompletion.md, Documentation/SwiftlyDocs.docc/uninstall-toolchains.md, Documentation/SwiftlyDocs.docc/update-toolchain.md, Documentation/SwiftlyDocs.docc/use-toolchains.md
- switched article titles to not use capitals all across
- made use of `swiftly` more consistently lower-case, including titles
- revised language in a few places to remove future or past tense phrasing or to make the wording more direct.
- broke up the paragraphs into one-sentence-per-line structure for easier reviewing.
- fixed an odd typo.
- tried to broadly maintain the existing voice, but remove some extra phrasing here and there and generally tighten up the content.
=> broad swiftly-doc content edit pass

Tools/build-swiftly-release/BuildSwiftlyRelease.swift
- Fixes #266 by adding a XML entry `<title>Swiftly</title>`
=> Add pkg title as "swiftly"

Sources/SwiftlyCore/Platform.swift, Tests/SwiftlyTests/PlatformTests.swift
Retaining swiftly in the path increases the probability that a tool might run the proxy again, resulting in circularities. Also, tools will locate programs in the path to try and find adjacent toolchain files that cannot be discovered in the swiftly bin directory.
Remove the swiftly bin directory from the path when proxying to help improve the experience with other tools.
=> Remove swiftly from the path during proxying

Package.swift, Sources/Swiftly/Proxy.swift, Sources/Swiftly/SelfUpdate.swift, Sources/SwiftlyCore/Platform.swift
Adopting this feature flag will be required in the future. 
See https://github.com/swiftlang/swift-build/pull/405
=> Enable MemberImportVisibility

Sources/SwiftlyCore/Platform.swift
=> Add SDKROOT when proxying on macOS based on xcrun information

Sources/Swiftly/ListAvailable.swift
fix: get `in use` toolchain from `selectToolchain` & parse `in use` separately
=> Fix list-available showing wrong toolchain in use (#314)

Sources/SwiftlyCore/StringExtensions.swift, Sources/SwiftlyCore/SwiftlyCore.swift, Tests/SwiftlyTests/StringExtensionsTests.swift
Issue #251 
Implemented automatic text wrapping functionality to ensure Swiftly's terminal output respects the current terminal width.
**Changes**
- Added `wrapText()` extension to String that reformats text to fit within a specified column width
- Integrated terminal width detection in the output system using ioctl and winsize
=> Improve word wrapping 

Package.swift, Sources/MacOSPlatform/MacOS.swift, Sources/SwiftlyCore/Commands.swift, Sources/SwiftlyCore/ModeledCommandLine.swift, Tests/SwiftlyTests/CommandLineTests.swift, Tests/SwiftlyTests/HTTPClientTests.swift, Tests/SwiftlyTests/SwiftlyTests.swift, Tools/build-swiftly-release/BuildSwiftlyRelease.swift
Swiftly has many different commands that it invokes in different parts of its code base, supporting tooling, and tests. This list includes tar, git, pkgutil, and dscl among several others.
For the most part these tools are called using arrays that are manually assembled at the call site. In order to exercise that callsite in tests the test must necessarily become "medium" size because it involves integration testing with that tool, instead of "small", which is where most tests should be. A small test of that array would verify that the length has the correct arguments, number, spelling, and order. Also, there are various types of string interpolation in these arrays, which limit the type-safety.
Introduce a new way of modeling command-line invocations using Swift types. Commands and …
=> Add a modeled command-line for better checking

Documentation/SwiftlyDocs.docc/swiftly-cli-reference.md, Sources/Swiftly/Init.swift, Sources/Swiftly/Install.swift, Sources/Swiftly/Link.swift, Sources/Swiftly/List.swift, Sources/Swiftly/ListAvailable.swift, Sources/Swiftly/Run.swift, Sources/Swiftly/Swiftly.swift, Sources/Swiftly/Unlink.swift, Sources/Swiftly/Update.swift, Sources/Swiftly/Use.swift, Sources/SwiftlyCore/Messages.swift, Sources/SwiftlyCore/Platform.swift, Tests/SwiftlyTests/LinkTests.swift, Tests/SwiftlyTests/UnlinkTests.swift
Adds two new commands, `swiftly unlink` and `swiftly link`, which will disable and reenable swiftly's management of the active toolchain.
The `unlink` command removes the symlinks to toolchain binaries in the swiftly bin directory that is in the user's path. This allows the rest of the `$PATH` to be searched for available toolchain installations, falling back to the system default. On macOS with Xcode installed this has the effect of falling back to the toolchain in the user's installed Xcode.
The `link` command reinstates the symlinks to the `inUse` toolchain, which allows swiftly to resume management of the active toolchain.
=> Add ability to temporarily unlink swiftly

Sources/LinuxPlatform/Linux.swift, Sources/SwiftlyCore/Commands.swift, Sources/SwiftlyCore/ModeledCommandLine.swift, Tests/SwiftlyTests/CommandLineTests.swift, Tests/SwiftlyTests/SwiftlyTests.swift, Tools/build-swiftly-release/BuildSwiftlyRelease.swift
Model the pkgbuild command with the usual structure used for other commands.
Provide a custom string convertible implementation for configuration so that the
configuration can be easily converted into a string for logging and comparison
purposes.
Create a runEcho() implementation for the build swiftly release script so that
commands can output their command-line to the log for reproducibility.
Add a model for the Linux getent command. Provide a convenience entries() method
that provides a table of the entries for better ease of use.
Model a small subset of the git command for use in the build swiftly release script and
testing of it.
=> Model additional system commands

.github/workflows/nightly_snapshot_check.yml, scripts/prep-gh-action.sh
From time-to-time swiftly will need to update the Swift toolchain. In preparation
for the update, it will be good to be able to track how well it is working with those
toolchains on a regular basis.
Add a scheduled workflow that will use the latest snapshot toolchain with the
main branch and verify how well it works. Include all of the usual platforms that
are verified in each pull request.
=> Smoke test swiftly on nightly snapshot toolchains

Sources/LinuxPlatform/Linux.swift, Sources/MacOSPlatform/MacOS.swift, Sources/Swiftly/Install.swift, Sources/SwiftlyCore/Commands.swift, Sources/SwiftlyCore/ModeledCommandLine.swift, Tests/SwiftlyTests/CommandLineTests.swift, Tests/SwiftlyTests/HTTPClientTests.swift, Tools/build-swiftly-release/BuildSwiftlyRelease.swift
Using the existing approach to model command execution this models
most of the other commands used in the swiftly production code and
scripts, and adds test cases for them.
=> Model remaining commands

Sources/SwiftlyCore/Platform.swift
When runProgramOutput produces an error the exit code, program
name, and arguments are captured in a RunProgramError. However,
the program is being set to the first argument instead of the program
name, and the arguments doesn't include that first argument.
Correctly set the program name to the be the program name, and
set the arguments to be the entire argument list so that the error is
clear, and has all of the details.
=> Place the correct program and arguments into RunProgramError

Sources/Swiftly/Install.swift
The `installer` tool fails to install the toolchain on macOS unless `.pkg` is present in the filename. Otherwise it produces the error: "Error - the package path specified was invalid"
Add the appropriate file extension when downloading the toolchain so the installer can use it correctly.
=> Append file extension to downloaded toolchain

Documentation/SwiftlyDocs.docc/swiftly-cli-reference.md, Sources/MacOSPlatform/MacOS.swift, Sources/Swiftly/Uninstall.swift, Tests/SwiftlyTests/RunTests.swift
The uninstall message would print:
`Uninstalling main-snapshot-2025-05-12...Uninstalling package in user home directory...`
Clean it up so the second half only prints with `--verbose`. Also clean up a test assertion to make it more specific.
=> Cleanup Uninstall message

Package.resolved, Package.swift
This just bumps the minimum versions of the OpenAPI dependencies to enable building on Windows (you will still hit NIO build issues, but that is expected). This should close #298.
=> Bump OpenAPI depdendencies to support building on Windows.

.unacceptablelanguageignore, Sources/Swiftly/Install.swift, Sources/Swiftly/Uninstall.swift, Sources/SwiftlyCore/FileLock.swift, Sources/SwiftlyCore/ProcessInfo.swift, Tests/SwiftlyTests/FileLockTests.swift
Fixes Issue #142 
- **Description**:
Serialize concurrent swiftly install commands with a simple file lock.
Adds a lightweight FileLock (using `Data.write(to: fileURL, options: .withoutOverwriting)`) and wraps the install routine so only one process installs at a time
=> Adding FileLock

Sources/LinuxPlatform/Linux.swift, Sources/MacOSPlatform/MacOS.swift, Sources/Swiftly/Init.swift, Sources/Swiftly/Install.swift, Sources/Swiftly/Link.swift, Sources/Swiftly/List.swift, Sources/Swiftly/ListAvailable.swift, Sources/Swiftly/Proxy.swift, Sources/Swiftly/SelfUpdate.swift, Sources/Swiftly/Uninstall.swift, Sources/Swiftly/Unlink.swift, Sources/Swiftly/Update.swift, Sources/Swiftly/Use.swift, Sources/SwiftlyCore/Platform.swift, Sources/SwiftlyCore/SwiftlyCore.swift
Fixes Issue: #378 
To control printing user facing messages to stdout or stderr created a new function `message` to internally delegate to print after formatting.
In a subsequent change we will control the output to stdout or stderr.
=> Refactoring output print to message

Documentation/SwiftlyDocs.docc/swiftly-cli-reference.md, Sources/Swiftly/OutputSchema.swift, Sources/Swiftly/Swiftly.swift, Sources/Swiftly/Use.swift, Sources/SwiftlyCore/OutputFormatter.swift, Sources/SwiftlyCore/SwiftlyCore.swift, Sources/SwiftlyCore/Terminal.swift, Tests/SwiftlyTests/SwiftlyCoreTests.swift, Tests/SwiftlyTests/SwiftlyTests.swift, Tests/SwiftlyTests/UseTests.swift
Issue #376 
Add Output formatter to switch between text and JSON
Add JSON output to `switftly use`
=> Add JSON output for use command

Documentation/SwiftlyDocs.docc/swiftly-cli-reference.md, Sources/Swiftly/ListAvailable.swift, Sources/Swiftly/OutputSchema.swift, Sources/Swiftly/Use.swift, Sources/SwiftlyCore/OutputFormatter.swift, Sources/SwiftlyCore/SwiftlyCore.swift, Tests/SwiftlyTests/OutputSchemaTests.swift, Tests/SwiftlyTests/SwiftlyCoreTests.swift, Tests/SwiftlyTests/UseTests.swift
- Fixes Issue #376 
- Description
Refactor `list-available` command to support JSON output format
=> Refactor list-available command to support json format

Documentation/SwiftlyDocs.docc/swiftly-cli-reference.md, Sources/Swiftly/List.swift, Sources/Swiftly/OutputSchema.swift, Sources/SwiftlyCore/OutputFormatter.swift, Tests/SwiftlyTests/ListTests.swift, Tests/SwiftlyTests/UseTests.swift
Fixes Issue #376 
Refactor the List command to support JSON output format.
=> Refactor list command to support json format

Documentation/SwiftlyDocs.docc/swiftly-cli-reference.md, Sources/Swiftly/Install.swift, Sources/Swiftly/JsonFileProgressReporter.swift, Sources/SwiftlyCore/FileManager+FilePath.swift, Tests/SwiftlyTests/InstallTests.swift, Tests/SwiftlyTests/JsonFileProgressReporterTests.swift
Fixes Issue #254 
- Added a JsonFileProgressReporter that writes progress updates and completion status as JSON lines to a file during toolchain installation.
- Integrated with `swiftly install`, allowing progress to be tracked.
- Implemented and tested progress reporting, including step updates, completion (success/failure), and file clearing.
=> Json Progress File

Tests/SwiftlyTests/InstallTests.swift
The nightly snapshot toolchain that's run nightly caught a concurrency problem
in one of the InstallTests that verifies that the pipes are working for the progress
files. Rework the tasks in the test so that it no longer has the concurrency problem.
=> Fix shared mutable state problem with install test

Tests/SwiftlyTests/CommandLineTests.swift
The test suite creates a tiny test suite with a custom user email. If a developer working on Swiftly has commit signing enabled, that tool will see that the committer email and the signing identity don't match, and will fail to sign the commit, causing the `testGit` test to fail.
Disabling gpg signing commits in the temporary test repo.
=> Tests: Disable Git Commit Signing in Tests

Sources/Swiftly/Run.swift, Sources/Swiftly/SelfUpdate.swift, Sources/Swiftly/Swiftly.swift
The run command can potentially be running any command and there might be
expected output on stderr that a message can corrupt. Remove the message
from this particular subcommand.
=> Remove swiftly update message from swiftly run command

Sources/MacOSPlatform/MacOS.swift, Sources/SwiftlyCore/ModeledCommandLine.swift, Tools/generate-command-models/GenerateCommandModels.swift
This PR addresses a few compiler warnings and includes a small refactor.
- Removed unnecessary `await` expressions where no async operations were occurring, resolving `No 'async' operations occur within 'await' expression` warnings
- Refactored `arg.names` parsing logic to use `compactMap(...).first`, replacing repetitive `filter(...).first` chains and eliminating a warning
- Replaced unused result from `sys.installer(...)` with `_`
- Replaced unused loop variable `key` with `_` in `for (key, value)` loop
=> Partial warning cleanup: remove unused awaits and refactor argument parsing

Sources/SwiftlyCore/HTTPClient.swift, Tools/build-swiftly-release/BuildSwiftlyRelease.swift
Our build jobs won't work unless we detect and add the https proxy into the HTTP client prior to downloading the lib archive dependency. We can reuse the `HTTPRequestExecutorImpl` to detect and use the proxy correctly
=> Detect HTTPS_PROXY in HTTPClient

Documentation/SwiftlyDocs.docc/swiftly-cli-reference.md, Sources/Swiftly/Uninstall.swift, Tests/SwiftlyTests/UninstallTests.swift
Allow specifying multiple toolchain selectors at once when using install.
`$ swiftly uninstall 6.1.1 6.1.2`
Issue: #412
=> Support multiple toolchain selectors with `uninstall`

README.md
Simply reorder some of the steps to uninstall swiftly. Namely swap the following steps:
* removing the `SWIFTLY_HOME_DIR` and `SWIFTLY_BIN_DIR`
* removing swiftly elements from profile files
As it stands, users could become lost during the install process after removing their profile sections as they might not be ably to locate the swiftly home and bin dirs after they update their profile
=> [Documentation] re-order uninstall instructions
